version: "3.9"

services:
  api:
    build: .
    container_name: mlops_tp_api
    ports:
          #en production
      - "${PORT:-8000}:${PORT:-8000}"
      # en local dev
      #- "8000:8000"
    environment:
      PYTHONPATH: /app/src
      # ajout de PORT pour que l'API puisse le lire au démarrage
      PORT: 8000

  streamlit:
    build: .
    container_name: mlops_tp_streamlit
    ports:
      - "8501:8501"
    environment:
      PYTHONPATH: /app/src
      DEFAULT_DATA_PATH: /app/data/synthetic_freelance_jobs.csv
      API_BASE_URL: http://api:8000
    depends_on:
      - api
    command: streamlit run /app/src/mlops_tp/streamlit/appStreamlit.py --server.address 0.0.0.0 --server.port 8501